version: '3.8'
services:
  apiapp:
    image: apiapp
    build:
      dockerfile: apiapp/Dockerfile
    ports:
      - "5002:80"
    environment:
      ASPNETCORE_URLS: "http://+"
    deploy:
      restart_policy:
        condition: on-failure
